# ===================================================================
# NetAgent - Inventario Dispositivi (RoaS 3 VLAN, 6 PC)
# ===================================================================

# --- CISCO CORE ROUTER (Router-on-a-Stick) ---
R1:
  connection_type: "cisco_telnet"
  host: "127.0.0.1"
  port: 5011
  vendor: "cisco_ios"
  username: "admin"
  password: "cisco"

# --- CISCO ACCESS SWITCH ---
SW1:
  connection_type: "cisco_telnet"
  host: "127.0.0.1"
  port: 5013
  vendor: "cisco_switch"
  username: "admin"
  password: "cisco"

# --- TERMINAL CLIENTS (VPCS) ---
PC1:
  connection_type: "vpcs_telnet"
  host: "127.0.0.1"
  port: 5006
  vendor: "vpcs"

PC2:
  connection_type: "vpcs_telnet"
  host: "127.0.0.1"
  port: 5002
  vendor: "vpcs"

PC3:
  connection_type: "vpcs_telnet"
  host: "127.0.0.1"
  port: 5004
  vendor: "vpcs"

PC4:
  connection_type: "vpcs_telnet"
  host: "127.0.0.1"
  port: 5008
  vendor: "vpcs"

PC5:
  connection_type: "vpcs_telnet"
  host: "127.0.0.1"
  port: 5010
  vendor: "vpcs"

PC6:
  connection_type: "vpcs_telnet"
  host: "127.0.0.1"
  port: 5009
  vendor: "vpcs"