devices:
  - name: PC1
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC2
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC3
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC4
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC5
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC6
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC7
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC8
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC9
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC10
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC11
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC12
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC13
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC14
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC15
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC16
    profile: vpcs
    interfaces:
      - name: eth0
  - name: PC17
    profile: vpcs
    interfaces:
      - name: eth0
  - name: R1
    profile: frrouting
    interfaces:
      - name: eth0
      - name: eth1
      - name: eth2
  - name: R2
    profile: frrouting
    interfaces:
      - name: eth0
      - name: eth1
      - name: eth2
  - name: IOU1
    profile: cisco_ios
    interfaces:
      - name: Ethernet0/0
      - name: Ethernet0/1
      - name: Ethernet0/2
  - name: IOU2
    profile: cisco_ios
    interfaces:
      - name: Ethernet0/0
      - name: Ethernet0/1
  - name: Switch1
    profile: cisco_switch
    interfaces:
      - name: Ethernet0/0
      - name: Ethernet0/1
      - name: Ethernet0/2
      - name: Ethernet0/3
  - name: Switch2
    profile: cisco_switch
    interfaces:
      - name: Ethernet0/0
      - name: Ethernet0/1
      - name: Ethernet0/2
      - name: Ethernet0/3
      - name: Ethernet1/0
  - name: Switch3
    profile: cisco_switch
    interfaces:
      - name: Ethernet0/0
      - name: Ethernet0/1
      - name: Ethernet0/2
      - name: Ethernet0/3
  - name: Switch4
    profile: cisco_switch
    interfaces:
      - name: Ethernet0/0
      - name: Ethernet0/1
      - name: Ethernet0/2
      - name: Ethernet0/3
  - name: Switch5
    profile: cisco_switch
    interfaces:
      - name: Ethernet0/0
      - name: Ethernet0/1
      - name: Ethernet0/2
      - name: Ethernet0/3
      - name: Ethernet1/0

links:
  - endpoints: ['PC3:eth0', 'Switch1:Ethernet0/0']
  - endpoints: ['PC1:eth0', 'Switch1:Ethernet0/2']
  - endpoints: ['PC4:eth0', 'Switch1:Ethernet0/1']
  - endpoints: ['Switch1:Ethernet0/3', 'R1:eth0']
  - endpoints: ['R1:eth2', 'Switch4:Ethernet0/0']
  - endpoints: ['Switch4:Ethernet0/1', 'PC7:eth0']
  - endpoints: ['Switch4:Ethernet0/2', 'PC8:eth0']
  - endpoints: ['Switch4:Ethernet0/3', 'PC9:eth0']
  - endpoints: ['R1:eth1', 'R2:eth1']
  - endpoints: ['R2:eth2', 'IOU1:Ethernet0/0']
  - endpoints: ['R2:eth0', 'Switch3:Ethernet0/0']
  - endpoints: ['Switch3:Ethernet0/3', 'PC6:eth0']
  - endpoints: ['Switch3:Ethernet0/2', 'PC2:eth0']
  - endpoints: ['Switch3:Ethernet0/1', 'PC5:eth0']
  - endpoints: ['IOU1:Ethernet0/2', 'IOU2:Ethernet0/0']
  - endpoints: ['IOU1:Ethernet0/1', 'Switch2:Ethernet0/0']
  - endpoints: ['Switch2:Ethernet0/2', 'PC10:eth0']
  - endpoints: ['Switch2:Ethernet0/1', 'PC11:eth0']
  - endpoints: ['Switch2:Ethernet0/3', 'PC16:eth0']
  - endpoints: ['Switch2:Ethernet1/0', 'PC17:eth0']
  - endpoints: ['IOU2:Ethernet0/1', 'Switch5:Ethernet0/1']
  - endpoints: ['Switch5:Ethernet0/0', 'PC14:eth0']
  - endpoints: ['Switch5:Ethernet0/2', 'PC15:eth0']
  - endpoints: ['Switch5:Ethernet0/3', 'PC12:eth0']
  - endpoints: ['Switch5:Ethernet1/0', 'PC13:eth0']